[package]
name = "tower-aws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
lambda_http = "0.7"
tower = "0.4"
url = "2"
